### PR TITLE
change all `6to5` references to `Babel`

### PR DESCRIPTION
**Pull request by stevemao**
There are references of 6to5 below.

### CODE REVIEW

**Comment by sindresorhus** [comment]
:-1: I don't see the point.

**Comment by gdi2290** [comment]
seo reasons

**Comment by stevemao** [comment]
"Square's esnext - next generation JavaScript to today's JavaScript transformer now a part of 6to5."

Here `6to5` needs to change to `babel` then

**Comment by sindresorhus** [comment]
> Here 6to5 needs to change to babel then

:+1:

**Comment by stevemao** [comment]
fair enough

**Comment by arthurvr** [comment]
Ping?

**Comment by stevemao** [comment]
@addyosmani

**Pull request merged**
